services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_USER: omar
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sakila
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    depends_on:
      - db
    container_name: fast_api
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"

